### ISSUE TITLE
Voronoi fails

### ISSUE THREAD

**Issue by dvdrbls** [yeataro/TD_Voronoi#1]
It doesn't work but only in the desktop recently built and in my old lap top it does, can't figure out why, only in the last 3 windows doesn't show the result, pretty new to the software but liked the script, any ideas why it doesn't work?

**Comment by yeataro** [comment]
If possible, some screenshots can be compared to determine which operators have problems. And also want to know the graphics card model used in the desktop environment where it does not work. Thank you.

**Comment by dvdrbls** [comment]
Hi, I'm using a Vega 56 and now that you mention it, it worked a few driver versions earlier, a glsl node send a compilation error, trying to change the shader version didn't have any effect, what can I do?

**Comment by yeataro** [comment]
Hi, You can help me post the path and name of the node that shows the compilation error, and copy and paste the text of the report of the compilation error here, and then I can try to solve the issue based on this information, thank you.

**Comment by dvdrbls** [comment]
[stat.txt](https://github.com/yeataro/TD_Voronoi/files/5647841/stat.txt)
![2020 12 05-14 31](https://user-images.githubusercontent.com/5351941/101262995-d43d0680-3707-11eb-9abd-fefa772ea559.png)
![Capture1](https://user-images.githubusercontent.com/5351941/101262996-d4d59d00-3707-11eb-8803-d95652cb879f.PNG)





This is what I got running the file i the desktop, is that enough to diagnose the issue?

**Comment by yeataro** [comment]
Hello, it would be great if you could post the text in this operator ( `/TD_Voronoi_v1_example/TD_Voronoi_v1_099/info3` ) . Its text reports in detail what errors occurred during compilation. thank you.

![image](https://user-images.githubusercontent.com/13723054/101266849-d21d8b00-378d-11eb-90a6-c1286efaa4c0.png)

(It is different from other Glsl TOPs in this project only in that it uses the built in uniform `uTDPass`, I guess this may be the problem)

**Comment by dvdrbls** [comment]
![IMG_20201205_181535.jpg](https://user-images.githubusercontent.com/5351941/101268194-09585180-3726-11eb-96e0-8c9c012c1ae0.jpg)

**Comment by yeataro** [comment]
I tried to fix it in 437d37d, can you help me pull the project and try it out, thank you.

**Comment by dvdrbls** [comment]
It worked! Thank you this is awesome
